name             = "postgres"
type             = "kubernetes_manifest"
namespace        = "logto"
dependencies     = ["postgres_image"]
manifest         = "./manifests/postgres.yaml"
max_auto_retries = 3

[health]
block_deploy = true
